services:
  - type: web
    name: car-service-node
    env: node
    plan: free
    # Clone full repo; build and run from subfolder so sibling assets (logo) are available
    buildCommand: |
      cd car_service_node
      npm install --production=false
    startCommand: |
      cd car_service_node
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      # If provided, app will use PostgreSQL for persistence (preferred on Render)
      # Create a Secret named DATABASE_URL in Render and set it to your Postgres connection string
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      - key: DATA_DIR
        value: /var/data
    healthCheckPath: /
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
